In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os

In [11]:
vaersdata = '/Users/sangeetajayakar/Springboard_Course/Files_for_second_capstone/2021VAERSDATA.csv'
vaerssymptoms = '/Users/sangeetajayakar/Springboard_Course/Files_for_second_capstone/2021VAERSSYMPTOMS.csv'
vaersvax = '/Users/sangeetajayakar/Springboard_Course/Files_for_second_capstone/2021VAERSVAX.csv'

In [7]:
import chardet
with open(vaersdata, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [8]:
vaers_data = pd.read_csv(vaersdata, encoding='ISO-8859-1')
vaers_data.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,916710,01/01/2021,MO,23.0,23.0,NaN,F,NaN,"Acute appendicitis, onset morning of 1/1/2021 ...",NaN,...,NaN,Hypothyroidism,NaN,NaN,2,01/01/2021,NaN,NaN,Y,NKDA
1,916720,01/01/2021,NY,23.0,23.0,NaN,M,NaN,Patient made statements that he was having a h...,NaN,...,NaN,NaN,unknown,NaN,2,01/01/2021,NaN,NaN,Y,NaN
2,916741,01/01/2021,AR,68.0,68.0,NaN,F,NaN,"on dec 22 I felt some myalgias, chills, fatigu...",NaN,...,had surgery R hand for advanced arthritis 11/1...,Rheumatoid arthritis - mostly affecting R wris...,NaN,NaN,2,01/01/2021,NaN,NaN,NaN,bee stings
3,916772,01/01/2021,GA,55.0,55.0,NaN,M,NaN,Vaccine on 12/22/2020 and started feeling bad ...,NaN,...,NaN,"HTN, Insomnia,High Cholesterol,",NaN,NaN,2,01/01/2021,NaN,Y,NaN,Codeine
4,916790,01/01/2021,TN,52.0,52.0,NaN,F,NaN,"Flushing, sweating, increased heart rate proce...",NaN,...,NaN,"Asthma, migraines",NaN,NaN,2,01/01/2021,NaN,NaN,Y,"Sulfa, shellfish"

In [9]:
vaers_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5351 entries, 0 to 5350
Data columns (total 35 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VAERS_ID      5351 non-null   int64
 1   RECVDATE      5351 non-null   object
 2   STATE         4449 non-null   object
 3   AGE_YRS       4350 non-null   float64
 4   CAGE_YR       3153 non-null   float64
 5   CAGE_MO       11 non-null     float64
 6   SEX           5351 non-null   object
 7   RPT_DATE      16 non-null     object
 8   SYMPTOM_TEXT  5351 non-null   object
 9   DIED          810 non-null    object
 10  DATEDIED      747 non-null    object
 11  L_THREAT      549 non-null    object
 12  ER_VISIT      3 non-null      object
 13  HOSPITAL      1747 non-null   object
 14  HOSPDAYS      1133 non-null   float64
 15  X_STAY        15 non-null     object
 16  DISABLE       329 non-null    object
 17  RECOVD        5046 non-null   object
 18  VAX_DATE      4904 non-null   object
 19  ONSET_DATE    4818 non-null   object
 20  NUMDAYS       4522 non-null   float64
 21  LAB_DATA      3170 non-null   object
 22  V_ADMINBY     5351 non-null   object
 23  V_FUNDBY      16 non-null     object
 24  OTHER_MEDS    2850 non-null   object
 25  CUR_ILL       2228 non-null   object
 26  HISTORY       3522 non-null   object
 27  PRIOR_VAX     114 non-null    object
 28  SPLTTYPE      2285 non-null   object
 29  FORM_VERS     5351 non-null   int64
 30  TODAYS_DATE   5318 non-null   object
 31  BIRTH_DEFECT  24 non-null     object
 32  OFC_VISIT     822 non-null    object
 33  ER_ED_VISIT   1493 non-null   object
 34  ALLERGIES     2479 non-null   object
dtypes: float64(5), int64(2), object(28)
memory usage: 1.4+ MB

In [10]:
vaers_data.describe()

,VAERS_ID,AGE_YRS,CAGE_YR,CAGE_MO,HOSPDAYS,NUMDAYS,FORM_VERS
count,5.351000e+03,4350.000000,3153.000000,11.000000,1133.000000,4522.000000,5351.000000
mean,9.683927e+05,57.091607,59.641611,0.136364,3.336275,24.695710,1.997010
std,3.119518e+04,20.498795,20.983655,0.237793,3.417488,689.221079,0.054605
min,9.167100e+05,0.330000,0.000000,0.000000,1.000000,0.000000,1.000000
25%,9.386440e+05,40.000000,42.000000,0.000000,1.000000,0.000000,2.000000
50%,9.720920e+05,56.000000,60.000000,0.000000,2.000000,1.000000,2.000000
75%,9.945030e+05,74.000000,77.000000,0.200000,4.000000,5.000000,2.000000
max,1.024853e+06,105.000000,105.000000,0.600000,36.000000,36896.000000,2.000000

In [12]:
vaers_symptoms = pd.read_csv(vaerssymptoms, encoding='ISO-8859-1')
vaers_symptoms.head()

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,916710,Appendicitis,23.1,Band neutrophil percentage increased,23.1,Surgery,23.1,White blood cell count increased,23.1,NaN,NaN
1,916720,Dysphagia,23.1,Dyspnoea,23.1,NaN,NaN,NaN,NaN,NaN,NaN
2,916741,Chills,23.1,Complex regional pain syndrome,23.1,Fatigue,23.1,Headache,23.1,Joint range of motion decreased,23.1
3,916741,Myalgia,23.1,Pain in extremity,23.1,Peripheral swelling,23.1,X-ray abnormal,23.1,NaN,NaN
4,916772,Feeling abnormal,23.1,SARS-CoV-2 test positive,23.1,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
vaers_symptoms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8640 entries, 0 to 8639
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   VAERS_ID         8640 non-null   int64
 1   SYMPTOM1         8640 non-null   object
 2   SYMPTOMVERSION1  8640 non-null   float64
 3   SYMPTOM2         7059 non-null   object
 4   SYMPTOMVERSION2  7059 non-null   float64
 5   SYMPTOM3         5775 non-null   object
 6   SYMPTOMVERSION3  5775 non-null   float64
 7   SYMPTOM4         4808 non-null   object
 8   SYMPTOMVERSION4  4808 non-null   float64
 9   SYMPTOM5         3992 non-null   object
 10  SYMPTOMVERSION5  3992 non-null   float64
dtypes: float64(5), int64(1), object(5)
memory usage: 742.6+ KB

In [15]:
vaers_vax = pd.read_csv(vaersvax, encoding='ISO-8859-1')
vaers_vax.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,916710,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))
1,916720,COVID19,MODERNA,011L20A,1,IM,AR,COVID19 (COVID19 (MODERNA))
2,916741,COVID19,PFIZER\BIONTECH,EH9899,1,SYR,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
3,916772,COVID19,PFIZER\BIONTECH,EJ1685,UNK,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
4,916790,COVID19,PFIZER\BIONTECH,NaN,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH))

In [16]:
vaers_vax.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5471 entries, 0 to 5470
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   VAERS_ID         5471 non-null   int64
 1   VAX_TYPE         5471 non-null   object
 2   VAX_MANU         5471 non-null   object
 3   VAX_LOT          3370 non-null   object
 4   VAX_DOSE_SERIES  5462 non-null   object
 5   VAX_ROUTE        3337 non-null   object
 6   VAX_SITE         3608 non-null   object
 7   VAX_NAME         5471 non-null   object
dtypes: int64(1), object(7)
memory usage: 342.1+ KB

In [17]:
#what vaccines are there?
vaers_vax['VAX_TYPE'].unique()

array(['COVID19', 'FLU4', 'DTAPHEPBIP', 'HIBV', 'RV1', 'UNK', 'FLUX',
       'MMR', 'VARZOS', 'DTAP', 'PPV', 'HPV9', 'CHOL', 'DT', 'TTOX',
       'FLU3', 'FLUC3', 'FLUC4', 'FLUR4', 'MNQ', 'HPV4', 'TDAP', 'FLUA3',
       'HEPA', 'VARCEL', 'FLUA4', 'HEP', 'PNC13'], dtype=object)

In [20]:
print(vaers_data.shape)
print(vaers_symptoms.shape)
print(vaers_vax.shape)

(5351, 35)
(8640, 11)
(5471, 8)